//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_H
#define METASPRITE_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_TILE_ORIGIN 0
#define sprite_TILE_W 8
#define sprite_TILE_H 16
#define sprite_WIDTH 64
#define sprite_HEIGHT 48
#define sprite_TILE_COUNT 56
#define sprite_PALETTE_COUNT 1
#define sprite_COLORS_PER_PALETTE 4
#define sprite_TOTAL_COLORS 4
#define sprite_PIVOT_X 32
#define sprite_PIVOT_Y 24
#define sprite_PIVOT_W 64
#define sprite_PIVOT_H 48

BANKREF_EXTERN(sprite)

extern const palette_color_t sprite_palettes[4];
extern const uint8_t sprite_tiles[896];

extern const metasprite_t* const sprite_metasprites[5];

#endif
